### ISSUE TITLE
Multple listing of Constituent Xrefs & links on Published Documents record view page

### ISSUE THREAD

**Issue by npicardo** [rsinghal/giza#136]
Many (but not all) Constituent names and links are appearing in triplicate on **pubdocs** record pages, i.e. under "Details, in "Jump To" links, and in "People" side panel.  

Example: 
http://giza.fas.harvard.edu/pubdocs/154/full/

![PubDoc_ConstituentXRefs](https://user-images.githubusercontent.com/24414099/108273302-5ce11580-7141-11eb-9295-ba3539bb3a34.jpg)

**Comment by rsinghal** [comment]
This is stemming from the data I am pulling out of TMS.  It's ultimately a result of the offloader making multiple thumbnails (as I'm pulling the thumbnail when getting the related constituent).  I'm working to figure out how to query the database to remove these duplications.
