### ISSUE TITLE
Replace generic B&W images with color photos/stills?

### ISSUE THREAD

**Issue by raronin** [rsinghal/giza#31]
Is it possible to swap out Heather's filler B&W images on the website?  We've pulled the following photos to replace the 4 generic images and put them in the “dbmedia\images\website” folder:

For “Introduction to Giza” page:  AAW2089.jpg
For “Archaeology at Giza” page:  A3669_NS.jpg   
For “The GizaCARD” page:  UPM_HLS_diary_p018.jpg
For “Contact Us” page:  AAW358.jpg

![aaw2089](https://cloud.githubusercontent.com/assets/24395652/20939131/9c874816-bbbb-11e6-91b2-09664c9f1ae1.jpg)
![a3669_ns](https://cloud.githubusercontent.com/assets/24395652/20939182/c51d6fb2-bbbb-11e6-985a-6f4430884c53.jpg)
![upm_hls_diary_p018](https://cloud.githubusercontent.com/assets/24395652/20939186/d14697be-bbbb-11e6-8173-343d5d4244b9.jpg)
![aaw358](https://cloud.githubusercontent.com/assets/24395652/20939196/d920fe5c-bbbb-11e6-8916-26b83c4ddb6e.jpg)

**Comment by rsinghal** [comment]
Yes, that shouldn't be an issue.

**Comment by raronin** [comment]
Excellent, thanks!  ☺
