### ISSUE TITLE
“Download PDF” link?

### ISSUE THREAD

**Issue by raronin** [rsinghal/giza#35]
For Bibliography pages, the “download PDF” link needs to be waaaaaaayyyyyyy more obvious (right now it’s only in the full view, at the bottom of the Details section. Ideally, clicking on the thumbnail should open the pdf.)

**Comment by raronin** [comment]
Something seems to be not working correctly on the Bibliography pages.  I think the thumbnails for the PDFs should be showing up (?) but they're not.  There's just a weird bar that, if you click on it, downloads the PDF.

**Comment by rsinghal** [comment]
I need a link or something.  I don't know what you are looking at.

**Comment by raronin** [comment]
http://giza-web.rc.fas.harvard.edu/pubdocs/156/intro/

**Comment by raronin** [comment]
Also:
http://giza-web.rc.fas.harvard.edu/pubdocs/80/intro/ 
http://giza-web.rc.fas.harvard.edu/pubdocs/109/intro/

**Comment by rsinghal** [comment]
There is something wrong with those images.  They need to be fixed on your end.

**Comment by raronin** [comment]
I'm not sure what is wrong.  They appear fine in TMS.  Can you be more specific?

**Comment by raronin** [comment]
OK, we figured out the problem: some images have "JPEG" rather than "jpeg" as the extension.  We will fix these asap.

**Comment by jkisala** [comment]
I believe I've now replaced all of the .JPGs with .jpg, so these should be fine now!
