### ISSUE TITLE
“Donate” page text

### ISSUE THREAD

**Issue by raronin** [rsinghal/giza#36]
Can we make visible all the donation possibilities again?  Even if not currently active, it looks better than just this blank page.

**Comment by rsinghal** [comment]
I think it will be confusing to have a non working form.  I can just change the text to something like - Coming soon!

**Comment by raronin** [comment]
Maybe just add "Contact us" and link it to the "Contact" page?

**Comment by rsinghal** [comment]
![screen shot 2016-12-22 at 2 31 13 pm](https://cloud.githubusercontent.com/assets/2371632/21437692/55b60a72-c853-11e6-9ea8-580c872ea6b6.png)
How's this?

**Comment by raronin** [comment]
Perfect!
