### ISSUE TITLE
Add to Resources page

### ISSUE THREAD

**Issue by raronin** [rsinghal/giza#38]
Hyperlinks (to EDSITEment, the NEH educational resource site):

"Egyptian Symbols and Figures: Scroll Paintings" (Grades K-2) 
https://edsitement.neh.gov/lesson-plan/egyptian-symbols-and-figures-scroll-paintings#sect-thelesson 

"Egypt's Pyramids: Monuments with a Message" (Grades 3-5) 
https://edsitement.neh.gov/lesson-plan/egypts-pyramids-monuments-message#sect-thelesson

**Comment by rsinghal** [comment]
The template for the Resources page looks like this: http://giza-web.rc.fas.harvard.edu/resources/, which a title and a description (and the quick links on the side).  Do you want to follow that?  If so, can you send the information following that pattern, or do you just want a simple list (and I will also get rid of the side box).

**Comment by raronin** [comment]
This is a little complicated.  For the new "Educational Resources" page (which we are likely going to want to pull out and make a top-level header menu item in the full-build), we will have links to various museum/institutional websites, which at least for now will just be:

[TITLE] Museum of Fine Arts, Boston 
[WEBSITE] mfa.org

We should also have the NEH's learning site:

[TITLE] EDSITEment (a project of the National Endowment for the Humanities)

with the 2 specific Egypt modules under it:

"Egyptian Symbols and Figures: Scroll Paintings" (Grades K-2)
https://edsitement.neh.gov/lesson-plan/egyptian-symbols-and-figures-scroll-paintings#sect-thelesson

"Egypt's Pyramids: Monuments with a Message" (Grades 3-5)
https://edsitement.neh.gov/lesson-plan/egypts-pyramids-monuments-message#sect-thelesson

**Comment by raronin** [comment]
We are also working on putting together some of our own learning modules/lesson plans, which will eventually end up here too.  However, we have just begun to discuss these and still don't know exactly what shape they will take.  So, for now, can we just keep it a simple list, and when we work with Heather on the full build, we will have a better idea of how to tailor this section (as well as My Giza) to accommodate the material?

**Comment by raronin** [comment]
As for the museum/institutional websites, we have:

The Ägyptisches Museum der Universität Leipzig (Germany) [www.gko.uni-leipzig.de/aegyptisches-museum/]
The Ashmolean Museum, Univeristy of Oxford (UK) [www.ashmolean.org/]
The Berlin Ägyptisches Museum (Germany) [www.smb.museum/en/museums-institutions/aegyptisches-museum-und-papyrussammlung/home.html]
The British Museum (UK) [www.britishmuseum.org/]
The Egyptian Museum, Cairo (Egypt) [www.sca-egypt.org/eng/MUS_Egyptian_Museum.htm]
The Grand Egyptian Museum (Egypt) [www.gem.gov.eg/]
The Kunsthistorisches Museum, Vienna (Austria) [www.khm.at/en/]
The Metropolitan Museum of Art (USA) [www.metmuseum.org/]
The Musée du Louvre (France) [www.louvre.fr/en]
The Museo Egizio, Turin (Italy) [www.museoegizio.it/en/]
The Museum of Fine Arts, Boston (USA) [www.mfa.org]
The Oriental Institute Museum of the University of Chicago (USA) [oi.uchicago.edu/]
The Peabody Museum of Archaeology and Ethnology, Harvard University (USA) [www.peabody.harvard.edu/]
The Petrie Museum of Egyptian Archaeology, University College London (UK) [www.ucl.ac.uk/museums/petrie]
The Phoebe A. Hearst Museum of Anthropology, University of California, Berkeley (USA) [hearstmuseum.berkeley.edu/]
The Roemer- und Pelizaeus-Museum, Hildesheim (Germany) [www.rpmuseum.de/]
The Royal Ontario Museum (Canada) [www.rom.on.ca/en]
The University of Pennsylvania Museum of Archaeology and Anthropology, Philadelphia (USA) [www.penn.museum/]
