### ISSUE TITLE
Homepage links

### ISSUE THREAD

**Issue by raronin** [rsinghal/giza#40]
On the homepage, the “New to Giza?  Explore Giza 3D” hyperlink should presumably link to the Giza Plateau 3D model page.  Also, the “View Giza 3D” video placeholder should link to the Giza Plateau 3D video.

**Comment by rsinghal** [comment]
I thought you didn't have the 3D video?

**Comment by raronin** [comment]
Sorry, that wasn't clear!!  I meant NOT the misbehaving interactive 3D video, but the animated tour video (GPH_3DP_Giza Plateau_tour in TMS). That video seems already to play smoothly on the prototype site and offers a good intro to Giza.

Regarding the interactive 3D video: because it is the interactivity that seems to be the big problem (sounds like hopefully Luke and Archimedes can figure out how to get around that?), for now Dave is just "canning" the interactive bits so the video should be playable like any other mp4 video on the site.  To that end, Dave just came by to ask if you could put the video (still under construction and currently in 4 separate segments) up on the site, so he can do some final testing asap.  We have put the 4 video segments into dbmedia\images\videos (GizaNarativeShot1_Halfrez, GizaNarativeShot2_Halfrez, GizaNarativeShot3_Halfrez, and GizaNarativeShot4_Halfrez); would you please let us know when they are up on the site so Dave can check them out?  And please let me know if I can clarify anything.  Thanks!

**Comment by raronin** [comment]
I see the “New to Giza? Explore Giza 3D” hyperlink is now correctly linking to the Giza Plateau 3D model; however, clicking the “View Giza 3D” video placeholder still brings up an error message.  Can this be made to link to the Giza Plateau 3D video (GPH_3DP_Giza Plateau_tour)?
