### ISSUE TITLE
Homepage videos not working on Firefox/Mac

### ISSUE THREAD

**Issue by jkisala** [rsinghal/giza#50]
The homepage videos don't play on older versions of Firefox (we have version 45 on several computers in the office; the current is 52) on Macs. Obviously this won't affect a huge number of users, but it would be great if we could get them working for at least the last couple releases, since not everyone (including us!) keeps their browser completely up to date.

Thanks,
Jeremy

**Comment by rsinghal** [comment]
There appears to be an issue with the mp4 version of the video (maybe an encoding issue?).  For now, I have hidden that version so the home page uses either the webm or ogv version of the video.  This is a temporary fix as I would like to figure out why Firefox is failing on the mp4, but in the meantime it is working again (may require a few refreshes to clear the cache).
