### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by npicardo** [rsinghal/giza#53]
Much later than anticipated, we've signed up for Google Analytics.  

Tracking number for the Digital Giza site =  UA-98043800-1

Universal Analytics tracking code:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98043800-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by rsinghal** [comment]
Added to dev and production.  Let me know if you don't see data start to populate your Google Analytics dashboard in the next few days.

**Comment by npicardo** [comment]
Hi Rashmi,

Wow, that was fast!  Thank you!
:-)

Cheers,
Nick
