### ISSUE TITLE
Sidebar photos on static pages

### ISSUE THREAD

**Issue by jkisala** [rsinghal/giza#55]
When viewing the website in Firefox on a Mac, the aspect ratio of images on the right sidebar of pages like Intro to Giza, The GizaCARD, etc. is messed up - they're displaying weirdly elongated.

**Comment by jkisala** [comment]
I just noticed that this is happening with image thumbnails in search results as well - see top screenshot, vs. how they look in Safari below (which is correct).

![firefox](https://cloud.githubusercontent.com/assets/24918912/25587535/84dd5f64-2e72-11e7-993a-8b27d2712884.jpg)

![safari](https://cloud.githubusercontent.com/assets/24918912/25587563/9fc0ad90-2e72-11e7-8b82-c525aab7aee1.jpg)

**Comment by rsinghal** [comment]
I can't recreate this behavior on Firefox on my Mac.  Can you confirm that it is still happening and include URLs for the search that you did as well as screenshots of the other pages?

**Comment by jkisala** [comment]
Interesting, it's not happening on my Mac at home, either. Maybe it's just my computer at work - I'll look into it on Monday and let you know if it's still an issue.

And I see you got the donate and contact links working, which is great. Thanks so much!

**Comment by jkisala** [comment]
Weirdly, it's now fine on my work computer as well. So whatever was going on I guess it was a temporary glitch, and we can close out this ticket. Thanks, Rashmi!
