### ISSUE TITLE
"old" production site URL still active

### ISSUE THREAD

**Issue by npicardo** [rsinghal/giza#59]
A recent google search revealed that the "old" URL (giza-web.rc.fas.harvard.edu) is still active in addition to giza.fas.harvard.edu, so google generates results for both separately.  Tested to see if they have the same target.  Many searches produce the same results; however, a blank simple search (totals for all data) produce different totals listed for "search results found" at top of results page:  145,994 on old URL but 145,998 on the new.  Faceted search category totals are identical via both URLs when broken down individually, but when added up they total 145,823.

**Comment by rsinghal** [comment]
giza-web is not the old production site - it's the dev site for testing purposes before pushing to production.  I can make that site not indexable by Google, but they may have different numbers depending on when the last data refresh happened on each of the servers.

**Comment by npicardo** [comment]
Hi Rashmi,

Ugh, sorry for my brain lapse about that URL.  If there’s value for you on the dev side to have it indexed by Google, I defer to your judgement on whether or not to make that change.  If there’s no major upside, probably better to cancel the indexing to prevent user-side confusion and to know that our analytics for the public prototype site represent all traffic.
Thanks for the explanation!
Cheers,
Nick

**Comment by npicardo** [comment]
Is it a concern that the displayed total items found for a search doesn’t match the combined faceted values for either of the site instances?

**Comment by rsinghal** [comment]
Agreed - no need for the dev site to be indexed.  I will get that in place sometime this week.  As for the search numbers and facets having different numbers, that could be a concern.  I will make it a separate ticket for later investigation.

**Comment by npicardo** [comment]
Awesome, thanks!

**Comment by rsinghal** [comment]
robots.txt added to giza-web
