### ISSUE TITLE
Add more IIIF content to the site

### ISSUE THREAD

**Issue by ColeDCrawford** [rsinghal/giza#95]
@npicardo might have info on

> Martin Uildriks’s progress building our offloader app to help with redirecting paths to our new images homes on DRS, etc. I think Martin felt he fixed the last remaining bug a couple of days ago.

Getting more IIIF content added will help substantially with testing.

**Comment by npicardo** [comment]
As of today, it appears there's one final hurdle to clear with the offloader in test scenarios.  I put Martin in touch with DRS today to see if they can help him identify a cause. We will move to test and deploy on the live Giza TMS as soon as it's resolved.

**Comment by ColeDCrawford** [comment]
Thanks @npicardo. Just adding Rashmi's comment here:

>  I think what would be helpful is if you could load all of the DRS IDs for one site (it can be a site with a small number of related photos).  The idea then would be clicking on each thumbnail in the Photos box would take the user directly to the Photo page, rather than the modal view we have right now (and is inefficient for sites that have thousands of images because it loads all of them ahead of time).
> 
> One of things I want to make sure is that photo that is set as primary display is displayed first in Mirador and I don't have any examples of that right now.

**Comment by npicardo** [comment]
The following TMS Media records have been updated with DRS info for IIIF:

All (10) media related to Site G 2408 (TMS site ID = 857)
Rendition Numbers
HUMFA_A866_NS
HUMFA_C3309_NS
HUMFA_C3310_NS
HUMFA_C3311_NS
HUMFA_EG000498
HUMFA_EG002029
HUMFA_EG013617
HUMFA_EG013618
HUMFA_EG019716
MFAB_AAW1446

**Comment by ColeDCrawford** [comment]
Update: offloader app is still not working. Someone (Peter or Nick?) is getting touch with Gallery Systems about the TMS thumbnail issue.

Library IIIF URLs are going to be changing in early 2021, so we will need to update manifests at that point regardless.
